### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by LuvForAirplanes** [randomfox/church-songbook#23]
What ya'll really need is a mobile app for Android...

@Jonathannathaokay What do you think?

**Comment by randomfox** [comment]
I think that is a good idea, I just don't know anything about creating mobile apps. And I know I'm not Jonathannathaokay ;)

**Comment by LuvForAirplanes** [comment]
Do you have a database (Postgres, MySql, etc) dump, or an Excel spreadsheet, CSV, TSV or something? I may be interested in writing something.
Would ya'll actually use this in-house? ;)

**Comment by randomfox** [comment]
No, There isn't a database. Not really, it was just something I decided to do and invited Jonathannathaokay.

**Comment by LuvForAirplanes** [comment]
OK. So basically, we would have to parse out the html to come up with a database. I do think people would have interest within our church though if we could come up with an app. (like searching text, search by meter, tune, etc) I would have interest in developing one, I just can't promise it now.

**Comment by randomfox** [comment]
OK.

**Comment by LuvForAirplanes** [comment]
Are you OK with my writing an app with the data you put together? I noted that it's GNU v3 so i figured it would be ok, but i just wanted to check.

**Comment by randomfox** [comment]
Yeah it's fine.
